appkey: quiwyeuqiweyrwqoiueyrqweoiury
lvdb: lv.db
debug: false
db:
  url: root:123456@/test?charset=utf8mb4&parseTime=True&loc=Local
sms:
  key: LTAITBp6uTMAfXA2
  secret: LDciOEtGumVXnc1CToFh6g8Wi2ecRH
  sign: 不学网  # 签名
  reg_tpl_code: SMS_155370082 # 注册模板编号
  loginTplCode: SMS_119082858 # 登录模板编号
wechat:
  id: wx98734283bb3e480f
  secret: e4fb077a6678bbb1101aec0791fde3b9